name:        galois-field
version:     1.0.1
synopsis:    Galois field library
description: An efficient implementation of Galois fields used in cryptography research
maintainer:  Adjoint Inc (info@adjoint.io)
license:     MIT
github:      adjoint-io/galois-field
category:    Cryptography

default-extensions:
  - LambdaCase
  - RecordWildCards
  - OverloadedStrings
  - NoImplicitPrelude
  - FlexibleInstances
  - FlexibleContexts
  - ScopedTypeVariables
  - RankNTypes
  - DataKinds
  - DeriveFunctor
  - DeriveGeneric
  - GeneralizedNewtypeDeriving
  - KindSignatures
  - MultiParamTypeClasses
  - OverloadedLists
  - PatternSynonyms
  - TypeFamilies

dependencies:
  - base             >= 4.10   && < 5
  - protolude        >= 0.2    && < 0.3
  - bitvec           >= 1.0.2  && < 1.1
  - groups           >= 0.4.1  && < 0.5
  - integer-gmp      >= 1.0.2  && < 1.1
  - mod              >= 0.1.0  && < 0.2
  - MonadRandom      >= 0.5.1  && < 0.6
  - QuickCheck       >= 2.13   && < 2.14
  - poly             >= 0.3.2  && < 0.4
  - semirings        >= 0.5    && < 0.6
  - wl-pprint-text   >= 1.2.0  && < 1.3
  - vector           >= 0.12.0 && <0.13

extra-source-files:
  - README.md
  - ChangeLog.md

ghc-options:
  - -freverse-errors
  - -O2
  - -Wall

library:
  exposed-modules:
    - Data.Field.Galois
  other-modules:
    - Data.Field.Galois.Base
    - Data.Field.Galois.Binary
    - Data.Field.Galois.Extension
    - Data.Field.Galois.Frobenius
    - Data.Field.Galois.Prime
    - Data.Field.Galois.Sqrt
    - Data.Field.Galois.Tower
    - Data.Field.Galois.Unity
  source-dirs:
    - src

tests:
  galois-field-tests:
    main: Main
    dependencies:
      - galois-field
      - tasty >= 1.2 && <1.3
      - tasty-quickcheck >= 0.10 && <0.11
    source-dirs:
      - test

benchmarks:
  galois-field-benchmarks:
    main: Main
    dependencies:
      - galois-field
      - criterion >= 1.5 && <1.6
    source-dirs:
      - bench
